redpen-cc/redpen

- redpen-core/src/main/java/cc/redpen/formatter/XMLFormatter.java
- redpen-core/src/main/java/cc/redpen/model/Section.java
- redpen-core/src/main/java/cc/redpen/model/Sentence.java
- redpen-core/src/main/java/cc/redpen/parser/LineOffset.java
- redpen-core/src/main/java/cc/redpen/parser/SentenceExtractor.java
- redpen-core/src/main/java/cc/redpen/parser/WikiParser.java
- redpen-core/src/main/java/cc/redpen/parser/markdown/CandidateSentence.java
- redpen-core/src/main/java/cc/redpen/parser/markdown/MergedCandidateSentence.java
- redpen-core/src/main/java/cc/redpen/parser/markdown/ToFileContentSerializer.java
- redpen-core/src/main/java/cc/redpen/validator/ValidationError.java
- redpen-core/src/main/java/cc/redpen/validator/section/DuplicatedSectionValidator.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/KatakanaSpellCheckValidator.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/SpaceBeginningOfSentenceValidator.java
- redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java
- redpen-core/src/test/java/cc/redpen/PlainTextParserTest.java
- redpen-core/src/test/java/cc/redpen/WikiParserTest.java
- redpen-core/src/test/java/cc/redpen/model/DocumentCollectionTest.java
- redpen-core/src/test/java/cc/redpen/model/DocumentTest.java
- redpen-core/src/test/java/cc/redpen/model/SectionTest.java
- redpen-core/src/test/java/cc/redpen/parser/LineOffsetTest.java
- redpen-core/src/test/java/cc/redpen/parser/markdown/MergedCandidateSentenceTest.java
Support line offset.
For example, given follwoing lines,  
* ito
* kato
The offset of first line is 2 and the offset of second line is 4.
> Markdown line offset support

- redpen-cli/src/main/java/cc/redpen/Main.java
I will change cli version to 1.1 from 1.0.1 since the RedPen output formats are going to be changed by issues such as #374 and #369.
> Bump redpen cli version to 1.1

- redpen-core/src/main/java/cc/redpen/parser/markdown/ToFileContentSerializer.java
- redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java
When markdown parser in redpen 1.1 experimental has the  following input document, the computed line number is wrong... 
Validator class is a abstract class in RedPen project.
Functions provided by RedPen class are implemented with validator class.
> Fix bug on line inconsistency in markdown parser

- redpen-cli/src/main/java/cc/redpen/Main.java
- redpen-core/src/main/java/cc/redpen/formatter/Formatter.java
- redpen-core/src/main/java/cc/redpen/formatter/JSONBySentenceFormatter.java
- redpen-core/src/main/java/cc/redpen/formatter/JSONFormatter.java
- redpen-core/src/main/java/cc/redpen/formatter/PlainBySentenceFormatter.java
- redpen-core/src/main/java/cc/redpen/formatter/XMLFormatter.java
- redpen-core/src/main/java/cc/redpen/parser/PlainTextParser.java
- redpen-core/src/test/java/cc/redpen/formatter/JSONFormatterTest.java
- redpen-server/src/main/java/cc/redpen/server/api/RedPenConfigurationResource.java
- redpen-server/src/main/java/cc/redpen/server/api/RedPenResource.java
- redpen-server/src/main/java/cc/redpen/server/api/WinkAPIDescriber.java
- redpen-server/src/main/webapp/css/redpen.css
- redpen-server/src/main/webapp/index.html
* Moved the "by sentence" formatter from the web server to an Formatter implementation (JSONBySentenceFormatter)
* Created a "by sentence" plain formatter (PlainBySentenceFormatter)
* Added the new formatters as redpen-cli output options json2 and plain2
* Modified PlainTextParser to add the offset within each line each Sentence appears to assist sorting errors by their position within a document
* Added a comment or two
* Added primitive sentence highlighting in the editor of the erroneous sentence on mouse-over
> Changes for the web demo GUI

- redpen-core/src/main/java/cc/redpen/formatter/JSONBySentenceFormatter.java
- redpen-core/src/main/java/cc/redpen/formatter/JSONFormatter.java
- redpen-core/src/main/java/cc/redpen/model/Sentence.java
- redpen-core/src/main/java/cc/redpen/parser/PlainTextParser.java
- redpen-core/src/main/java/cc/redpen/parser/SentenceExtractor.java
- redpen-core/src/main/java/cc/redpen/parser/markdown/ToFileContentSerializer.java
- redpen-core/src/main/java/cc/redpen/tokenizer/JapaneseTokenizer.java
- redpen-core/src/main/java/cc/redpen/tokenizer/TokenElement.java
- redpen-core/src/main/java/cc/redpen/tokenizer/WhiteSpaceTokenizer.java
- redpen-core/src/main/java/cc/redpen/validator/Validator.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/ContractionValidator.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/DoubledWordValidator.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/InvalidWordValidator.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/KatakanaEndHyphenValidator.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/SpaceBeginningOfSentenceValidator.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/SpellingValidator.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/SuccessiveWordValidator.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/SymbolWithSpaceValidator.java
- redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java
- redpen-core/src/test/java/cc/redpen/PlainTextParserTest.java
- redpen-core/src/test/java/cc/redpen/WikiParserTest.java
- redpen-core/src/test/java/cc/redpen/formatter/JSONBySentenceFormatterTest.java
- redpen-core/src/test/java/cc/redpen/parser/SentenceExtractorTest.java
- redpen-core/src/test/java/cc/redpen/parser/markdown/MergedCandidateSentenceTest.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/InvalidSymbolValidatorTest.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/SymbolWithSpaceValidatorTest.java
- redpen-server/src/main/webapp/css/redpen.css
- redpen-server/src/main/webapp/index.html
* Rewrote PlainTextParser to parse in such a way that a LineOffset map could be constructed whilst parsing, meaning offset lookups for token positions now match their position in the source text.
* Offsets generated for plain text documents are now relative to the line, rather than the sentence, as they are for Markdown/WIKI documents.
* Added Sentence.getOffsetPosition() method to do a reverse lookup of a LineOffset and provide its position in Sentence.getContent()’s string.
* Added “subsentence” element to JSON2 format to help implementers display the error within the sentence text provided in the JSON in case access to the source text is difficult in-situ.
* Added test cases for new functionality
* Patched faulty append() of source document text in jQuery
* Updated UI to match the …
> Support for offsets in plain text documents

- redpen-core/src/main/java/cc/redpen/ConfigurationLoader.java
- redpen-core/src/main/java/cc/redpen/config/Configuration.java
- redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java
- redpen-core/src/test/java/cc/redpen/config/ConfigurationRedPenBuilderTest.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/InvalidSymbolValidatorTest.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/QuotationValidatorTest.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/SymbolWithSpaceValidatorTest.java
ConfigurationBuilder mutation methods now throw IllegalStateException after calling build().
ConfigurationBuilder is not designed to build more than one RedPen instance.
Adding validatorConfig / symbol to ConfigurationBuilder could effect existing RedPen instance.
> configuration-immutable

- redpen-server/src/main/java/RedPenRunner.java
#431 add ShutdownHandler when "stop.key" is supplied by CLI
You can shutdown RedPen server with the following command(only from loopback address):
$ curl -d "token=[stop key]" http://127.0.0.1:8080/shutdown
See also: Jetty document - Shutdown Handler
http://www.eclipse.org/jetty/documentation/current/shutdown-handler.html
> #431 add ShutdownHandler when "stop.key" is supplied by CLI

- .travis.yml
- redpen-core/src/main/java/cc/redpen/validator/JavaScriptValidator.java
- redpen-core/src/main/java/cc/redpen/validator/Validator.java
- redpen-core/src/test/java/cc/redpen/validator/JavaScriptValidatorTest.java
- redpen-core/src/test/resources/cc/redpen/validator/error-messages.properties
- redpen-core/src/test/resources/cc/redpen/validator/error-messages_ja.properties
Introduce JavaScriptValidator.
files which name end with ".js" and located in "js" (can be specified with "script-path" property) directory will be treated as JavaScript validator implementation. Functions with the following signature will be called upon validation time:
var message = "validation error message {0}";
function preValidateSentence(sentence) {
}
function preValidateSection(section) {
}
function validateDocument(errors, document) {
}
function validateSentence(errors, sentence) {
}
function validateSection(errors, section) {
}
> Introduce JavaScriptValidator.

- redpen-core/pom.xml
- redpen-core/src/main/java/cc/redpen/model/Sentence.java
- redpen-core/src/main/java/cc/redpen/parser/AsciiDocParser.java
- redpen-core/src/main/java/cc/redpen/parser/DocumentParser.java
- redpen-core/src/main/java/cc/redpen/parser/PlainTextParser.java
- redpen-core/src/main/java/cc/redpen/validator/Validator.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/SpellingValidator.java
- redpen-core/src/main/java/org/asciidoctor/RedPenTreeProcessor.java
- redpen-core/src/test/java/cc/redpen/AsciiDocParserTest.java
- redpen-core/src/test/java/cc/redpen/PlainTextParserTest.java
- redpen-server/src/main/webapp/css/redpen.css
- redpen-server/src/main/webapp/index.html
These additions utilize the Ruby parser from the AsciiDoctor project to provide RedPen with basic validation of the none-markup elements of a user's AsciiDoc documents.
It includes updates to the web demo GUI to demonstrate AsciiDoc support.
There is a small issue with offset calculations for the end position of errors when the error is towards the end of an inline element or the end of a sentence, but this issue is caused by how RedPen calculates the end position of errors - we should review that.
> AsciiDoc Parser support

- redpen-cli/src/main/java/cc/redpen/Main.java
Note that default input format (plain) is not changed.
> Detect markdown (.md) as input format

- redpen-cli/src/main/assembly/executable.xml
This is a hotfix for redpen-distribution package.
> Output dir in redpen-cli

- redpen-core/pom.xml
- redpen-core/src/main/java/cc/redpen/tokenizer/JapaneseTokenizer.java
We are planning on publishing Kuromoji to Maven Central soon.  As part of this, it would be great to test it in a few projects before we release it.  This pull-requests contains changes that uses `kuromoji-ipadic` from the release candidate from Sonatype's staging repository.
> Prepare for using Kuromoji being from Maven Central

- redpen-distribution/pom.xml
module redpen-distribution requires Maven 3.0 or later
explicitly describe in pom.xml
> module redpen-distribution requires Maven 3.0 or later

- redpen-server/bin/redpen-server
Use /tmp as $REDPEN_LOG_DIR if $REDPEN_HOME/logs is unavailable.
> Check the write permission of $REDPEN_LOG_DIR.

- redpen-core/src/main/java/cc/redpen/parser/markdown/ToFileContentSerializer.java
- redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java
> Skip to validate sentences in blockquote in Markdown parser

- redpen-cli/sample/js/test/redpen.js
- redpen-cli/sample/js/test/validator-js-test.js
test case implementation example for JavaScript Validators.
redpen.js : utlity script for testing JavaScript validators
validator-js-test.js : tests validator.js
> test case implementation example for JavaScript Validators 

- redpen-core/src/main/java/cc/redpen/model/Section.java
- redpen-core/src/main/java/cc/redpen/parser/AsciiDocParser.java
- redpen-core/src/main/java/org/asciidoctor/RedPenTreeProcessor.java
- redpen-core/src/test/java/cc/redpen/AsciiDocParserTest.java
This patch prevents the validator from validating asciidoc blocks.
It also provides a workaround to an existing issue where the last line number would be incorrectly calculated by asciidoctorj (the java wrappings used to access the asciidoctor parser).
I added a check for adding list items when a list block had not been created - this was causing an exception in redpen code that was being called by JRuby, which manifested in redpen as 
```
Asciidoctor parser error: (TypeError) exception class/object expected
```
There is still an outstanding issue with asciidoctorj that causes the error
```
org.asciidoctor.ast.SectionImpl cannot be cast to org.jruby.RubyObject
```
This is more complex to resolve as it reflects a defect in asciidoctorj. We may need to rethink the asciidoc parser somewhat.
> Fix for #507 - do not process quoted blocks (ie: source listings etc)

- redpen-core/src/main/java/cc/redpen/validator/ExpressionRule.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/OkuriganaValidator.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/OkuriganaValidatorTest.java
This patch fixes an OkuriganaValidator bug reported in Issue #517.
> Fix a bug on OkuriganaValidator (#517)

- redpen-core/src/main/java/cc/redpen/validator/JavaScriptValidator.java
- redpen-core/src/test/java/cc/redpen/validator/JavaScriptValidatorTest.java
Hello,
This is my first attempt to secure the JS validator facility.
I think JS based validators are good to have, but at the same time I feel it's better to have runtime enviroments confined somehow.  I have written some working exploits for RedPen 1.3 or later; if you are interested in, I'll show you.
Changes are:
- Disable intrinsic Java bridging facilities in order to execute validators
- Disable intrinsic function to load JS or enable Rhino compatibility in order to execute validators
Please review and hopefully merge.  Keep up good work.
Best,
-t
> Sandboxing JavaScript runtime environment

- redpen-core/src/main/java/cc/redpen/validator/JavaScriptValidator.java
- redpen-server/src/test/java/cc/redpen/server/api/RedPenResourceTest.java
- redpen-server/src/test/resources/js/pass.js
Hello,
I've fixed the recent breakage of JS validator facility. 
Background:
Currently RedPen seems to choke on executing JS based validators in normal mode operation with RuntimeException.
The RuntimeException originates from the ClassNotFoundException, which occurs during the sandboxing process if the JavaScriptValidatorTest class does not exist (i.e. normal mode.)
(The stack trace:  [stacktrace.txt](https://github.com/redpen-cc/redpen/files/56624/stacktrace.txt))
Changes are:
- redpen-core/src/main/java/cc/redpen/validator/JavaScriptValidator.java: Guarding against ClassNotFoundException based RuntimeException upon test class exposure.
- redpen-server/src/test/java/cc/redpen/server/api/RedPenResourceTest.java: Running JS validators through the JSON …
> Fixing JS validator failure case

- redpen-core/src/main/java/cc/redpen/validator/JavaScriptValidator.java
use File.separator instead of '/' for the better multi-OS support.
> use File.separator instead of '/' for the better multi-OS support.

- redpen-core/src/main/java/cc/redpen/config/Configuration.java
- redpen-core/src/main/java/cc/redpen/config/SymbolTable.java
- redpen-core/src/test/java/cc/redpen/config/ConfigurationTest.java
- redpen-core/src/test/java/cc/redpen/config/SymbolTableTest.java
- redpen-server/pom.xml
- redpen-server/src/main/java/cc/redpen/server/api/RedPenConfigurationResource.java
- redpen-server/src/main/java/cc/redpen/server/api/RedPenService.java
- redpen-server/src/main/resources/conf/redpen-conf-ja-hankaku.xml
- redpen-server/src/main/resources/conf/redpen-conf-ja-zenkaku2.xml
- redpen-server/src/test/java/cc/redpen/server/api/RedPenConfigurationResourceTest.java
- redpen-server/src/test/java/cc/redpen/server/api/RedPenResourceTest.java
- redpen-server/src/test/java/cc/redpen/server/api/RedPenServiceTest.java
Also include default configurations for hankaku and zenkaku2 types.
> Expose symbol types in RedPen Server API

- redpen-core/src/main/java/cc/redpen/util/LanguageDetector.java
- redpen-core/src/main/java/cc/redpen/util/StringUtils.java
- redpen-core/src/test/java/cc/redpen/util/LanguageDetectorTest.java
- redpen-server/src/main/java/cc/redpen/server/api/RedPenResource.java
- redpen-server/src/main/webapp/js/redpen.js
- redpen-server/src/test/java/cc/redpen/server/api/RedPenResourceTest.java
Language detection is more advanced now and also detects Japanese variants: zenkaku, zenkaku2 and hankaku.
> Language detection in Java

- .gitignore
- pom.xml
- redpen-cli/pom.xml
- redpen-core/pom.xml
- redpen-core/src/main/java/cc/redpen/RedPen.java
- redpen-core/src/main/java/cc/redpen/util/DictionaryLoader.java
- redpen-core/src/main/java/cc/redpen/validator/JavaScriptValidator.java
- redpen-core/src/test/java/cc/redpen/util/DictionaryLoaderTest.java
- redpen-core/src/test/java/cc/redpen/validator/JavaScriptValidatorTest.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/KatakanaEndHyphenValidatorTest.java
- redpen-distribution/pom.xml
- redpen-plugin/pom.xml
- redpen-server/pom.xml
load dictionary files and JavaScript valdiators only from directories under $REDPEN_HOME for the security reasons
Allowing clients to specify any file can be vulnerable.
This fix will lower the risk.
> load dictionary files and JavaScript valdiators only from directories under $REDPEN_HOME for the security reasons

- redpen-core/src/test/java/cc/redpen/validator/sentence/SymbolWithSpaceValidatorTest.java
- redpen-server/src/main/java/cc/redpen/server/api/CORSFilter.java
- redpen-server/src/main/webapp/WEB-INF/web.xml
- redpen-server/src/test/java/cc/redpen/server/api/CORSFilterTest.java
so that RedPen API can be used from a different domain - allows for a proxy-less communication with RedPen Server from WordPress Plugin
> Allow CORS (Cross-Origin AJAX requests)

- redpen-server/bin/redpen-server
redpen-server script didn't export $REDPEN_HOME, and JavaScriptValidator was trying to read JavaScript validators from bin/js, not $REDPEN_HOME/js.
> export REDPEN_HOME so that RedPenServer can read with getEnv

- redpen-core/src/main/java/cc/redpen/config/Configuration.java
- redpen-core/src/main/java/cc/redpen/config/ConfigurationLoader.java
- redpen-core/src/test/java/cc/redpen/config/ConfigurationTest.java
- redpen-server/src/main/java/cc/redpen/server/api/RedPenResource.java
- redpen-server/src/main/java/cc/redpen/server/api/RedPenService.java
- redpen-server/src/test/java/cc/redpen/server/api/RedPenResourceTest.java
- redpen-server/src/test/java/cc/redpen/server/api/RedPenServiceTest.java
Introduce secure mode to Configuration.findFile(), which is needed in redpen-server to disallow loading of arbitrary files with user-provided config.
User can specify file paths using "dict" attribute for many validators, forcing the server to read these files from its own filesystem, potentially giving the possibility to the user to derive whether some content is there or not.
> Improve redpen-server security

- redpen-core/src/main/java/cc/redpen/config/Configuration.java
- redpen-core/src/main/java/cc/redpen/validator/ValidatorFactory.java
- redpen-core/src/test/java/cc/redpen/config/ConfigurationTest.java
- redpen-core/src/test/java/cc/redpen/validator/ValidatorFactoryTest.java
Introduces new API in ConfigurationBuilder that registers all available validators for a particular language.
> Be able to support all available validators in external editors/wordpress

- redpen-core/src/main/java/cc/redpen/validator/Validator.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/DoubledWordValidator.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/DoubledWordValidatorTest.java
This is useful for automatically skipping commas, "a", "an", "to" etc, without providing skip lists for all major languages.
For example, we don't have a skip list for Russian yet, but this change already fixes all incorrectly reported cases.
> Allow specifying minimum length of detected doubled words

- redpen-core/src/main/java/cc/redpen/validator/sentence/SymbolWithSpaceValidator.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/SymbolWithSpaceValidatorTest.java
> Do not require after space if it is at the end of sentence

- redpen-core/src/main/java/cc/redpen/validator/sentence/SuggestExpressionValidator.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/SymbolWithSpaceValidator.java
- redpen-core/src/test/java/cc/redpen/validator/BaseValidatorTest.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/SpaceBeginningOfSentenceValidatorTest.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/SuggestExpressionValidatorTest.java
Otherwise if it suggests changing of "info" to "information", then it reports "**info**rmation" as error again.
> SuggestExpressionValidator should do whole matches only

- redpen-core/src/main/java/cc/redpen/validator/sentence/SpellingValidator.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/SpellingValidatorTest.java
but keep them as part of words (e.g. hyphens or apostrophes)
> SpellingValidator must skip all separate punctuation characters

- redpen-core/pom.xml
- redpen-server/pom.xml
- redpen-server/src/main/java/RedPenRunner.java
redpen-server should depend on commons-cli and jetty in "compile" scope.
redpen-server doesn't run without those libraries.
> adjust dependency scopes of redpen-server module

- redpen-core/src/main/java/cc/redpen/parser/latex/Lexer.java
- redpen-core/src/test/java/cc/redpen/LaTeXParserTest.java
- redpen-core/src/test/java/cc/redpen/parser/latex/LexerTest.java
Hello, I've noticed the LaTeX lexer doesn't process comment lines properly, giving off issues like #626.
I think more proper ways of processing comment lines should boil down to the following points:
1) Treat a comment line as a newline (or whitespace).
2) If one trails exactly one newline, ignore the line completely.
So I have changed comment handling in the lexer.
Thanks.
Changes:
- src/main/java/cc/redpen/parser/latex/Lexer.java: Changing comment handling.
- src/test/java/cc/redpen/parser/latex/LexerTest.java: Adding tests.
> Lexing comments in more compatible way

- redpen-core/src/main/java/cc/redpen/model/Document.java
- redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java
I made header contents in sections tokenized. This patch fixes #628.
> Make header contents tokenized in Document.builder

- redpen-core/src/main/java/cc/redpen/model/Document.java
- redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java
> Make contents in list elements tokenized in Document.builder

- redpen-server/src/main/java/cc/redpen/server/api/RedPenResource.java
- redpen-server/src/main/webapp/css/redpen.css
- redpen-server/src/main/webapp/index.html
- redpen-server/src/main/webapp/js/redpen-ui.js
- redpen-server/src/main/webapp/js/redpen.js
This change adds an extra tab to the redpen web UI that lets a user explore how the Japanese and white-space tokenizers break up words, and what attributes they reveal.
This is related to #614
> Addition of Tokenizer UI to redpen-server

- redpen-core/src/main/java/cc/redpen/validator/sentence/JapaneseNumberExpressionValidator.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/JapaneseNumberExpressionValidatorTest.java
Hello, I've fixed JapaneseNumberExpression so that it does not look into chained kanjis.
This PR intends to resolve #659 .
Please review and merge.
Thanks.
-t
Changes:
- redpen-core/src/main/java/cc/redpen/validator/sentence/JapaneseNumberExpressionValidator.java: Regex fixup.
- redpen-core/src/test/java/cc/redpen/validator/sentence/JapaneseNumberExpressionValidatorTest.java: Added test case.
> Number expresions should not precede kanjis

- redpen-core/src/main/java/cc/redpen/validator/section/GappedSectionValidator.java
- redpen-core/src/test/java/cc/redpen/validator/section/GappedSectionValidatorTest.java
Hello, I've fixed GappedSection so that it allows non-top headers to start document.
This PR intends to resolve #657.
Please review and merge.
Thanks.
-t
Changes:
- redpen-core/src/main/java/cc/redpen/validator/section/GappedSectionValidator.java: Latching on the first header level.
- redpen-core/src/test/java/cc/redpen/validator/section/GappedSectionValidatorTest.java: Added test case.
> Allowing non-top headers to start document

- redpen-server/src/test/java/cc/redpen/server/api/RedPenResourceTest.java
testJSValidatorRuns fails when it executed from IntelliJ IDEA.
Beause IntelliJ IDEA sets current directory to project root, and the test case fails to find js validator.
> run tests from IDEA

- redpen-core/src/main/java/cc/redpen/validator/Validator.java
The `NumberOfCharactersLocalizedValidatorTest` test checks for `Sentence is longer than 1,000 characters long.` which only works in locales that have a comma as thousands separator (and a dot for the decimal point).
In Locales like DE (and most other European ones) this is a dot as separator and the comma for the decimal comma.
The issue is that `MessageFormat.format` is not taking the locale of the Validator into consideration.
> Make sure the message obtained is in validators locale.

- redpen-core/src/main/java/cc/redpen/parser/latex/StreamParser.java
- redpen-core/src/test/java/cc/redpen/parser/latex/StreamParserTest.java
Hello,
I've changed LaTeX parser so that it ignores the \footnote command.
Thank you.
-t
Changes:
- redpen-core/src/main/java/cc/redpen/parser/latex/StreamParser.java: Adding \footnote to ignore list.
- redpen-core/src/test/java/cc/redpen/parser/latex/StreamParserTest.java: Adding test case.
> Ignoring LaTeX \footnote

- redpen-core/src/main/java/cc/redpen/RedPen.java
- redpen-core/src/main/java/cc/redpen/parser/PreprocessorRule.java
- redpen-core/src/main/java/cc/redpen/validator/JavaScriptLoader.java
- redpen-core/src/main/java/cc/redpen/validator/JavaScriptValidator.java
- redpen-core/src/main/java/cc/redpen/validator/ValidationError.java
- redpen-core/src/main/java/cc/redpen/validator/Validator.java
- redpen-core/src/main/java/cc/redpen/validator/ValidatorFactory.java
- redpen-core/src/test/java/cc/redpen/validator/EmbeddedJavaScriptValidatorTest.java
- redpen-core/src/test/java/cc/redpen/validator/JavaScriptValidatorTest.java
- redpen-core/src/test/resources/cc/redpen/validator/MyEmbeddedJS.js
- redpen-core/src/test/resources/cc/redpen/validator/error-messages.properties
- redpen-core/src/test/resources/cc/redpen/validator/error-messages_ja.properties
- redpen-core/src/test/resources/cc/redpen/validator/section/MyEmbeddedJSSection.js
- redpen-core/src/test/resources/cc/redpen/validator/sentence/MyEmbeddedJSSentence.js
- redpen-server/src/test/java/cc/redpen/server/api/RedPenResourceTest.java
ValidatorFactory to load embedded JavaScript validators located in resources/cc/redpen/validator/(section|sentence)
> ability to load embedded JavaScript Validators located in resources/cc/redpen/validator/(section|sentence)

- redpen-core/src/main/java/cc/redpen/validator/Validator.java
- redpen-core/src/main/java/cc/redpen/validator/sentence/SpaceBetweenAlphabeticalWordValidator.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/SpaceBetweenAlphabeticalWordValidatorTest.java
Add skip character of SpaceBetweenAlphabeticalWordValidator.
* skip_before_chars
* skip_after_chars
```
iPhone は iPod・携帯電話・インターネットの融合。
```
```
<validator name="SpaceBetweenAlphabeticalWord">
<property name="skip_before_chars" value="。、・（「『"/>
<property name="skip_after_chars" value="。、・）」』"/>
</validator>
```
> Enhance SpaceBetweenAlphabeticalWordValidator

- redpen-core/src/main/java/cc/redpen/config/ConfigurationLoader.java
- redpen-core/src/test/java/cc/redpen/config/ConfigurationLoaderTest.java
Ref #777.
When the ConfigurationLoader found duplicated configurations of validators:
- log a warn message
- use the latter configuration
> Detect duplicated validator configuration which resolves #777

- redpen-core/src/main/java/cc/redpen/validator/sentence/KatakanaEndHyphenValidator.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/KatakanaEndHyphenValidatorTest.java
This fix is to add special handling for Katakana words ends with small character such as "メニュー" or    "シチュー".
> Add special handling for small letter in KatakanaEndHypen

- redpen-core/pom.xml
In my environment (`LANG=ja_JP.UTF-8`), some tests are failed because the default locale is not properly set.
Here is the Maven log (excerpt):
```
$ ./mvnw test
...
Results :
Failed tests:   testErrorMessageIsProperlyFormatted(cc.redpen.validator.sentence.SuggestExpressionValidatorTest): expected:<[Found invalid word "info". Use the synonym "information" instead.]> but was:<[不正な単語 "info" がみつかりました．かわりに "information" を利用してください。]>
noErrorsForShortWordsByDefault(cc.redpen.validator.sentence.DoubledWordValidatorTest): expected:<[Found repeated word "validator".]> but was:<[一文に二回以上利用されている単語 "validator" がみつかりました。]>
testDoubledWordWithDifferentCase(cc.redpen.validator.sentence.DoubledWordValidatorTest): expected:<[Found repeated word "good".]> but was:<[一文に二回以上利用されている単語 "good" がみつかりました。]> …
```
> Set default locale to 'en-US' for testing

- redpen-core/src/main/java/cc/redpen/validator/section/EmptySectionValidator.java
- redpen-core/src/main/java/cc/redpen/validator/section/VoidSectionValidator.java
- redpen-core/src/test/java/cc/redpen/validator/section/EmptySectionValidatorTest.java
Fix error message of EmptySection (and VoidSection) to flush section names.
> Fix bugs to flush error for level 0 section

- redpen-core/src/main/java/cc/redpen/validator/sentence/JapaneseJoyoKanjiValidator.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/JapaneseJoyoKanjiValidatorTest.java
> Add list property of JapaneseJoyoKanji

- .slugignore
Fix the following error deploying RedPen to Heroku.
```
-----> Compressing...
!     Compiled slug size: 555.9M is too large (max is 500M).
!     See: http://devcenter.heroku.com/articles/slug-size
!     Push failed
```
> Add redpen-plugin module in .slugignore

- redpen-core/src/main/java/cc/redpen/validator/sentence/SpaceBetweenAlphabeticalWordValidator.java
I found that  SpacebwtweeenAlphabeticalWord does not work in redpen.herokuapp.com. This is the hot fix.
> Fix a bug of SpacebwtweeenAlphabeticalWord

- redpen-core/src/main/java/cc/redpen/parser/markdown/ToFileContentSerializer.java
- redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java
> Hotfix reference link

- redpen-cli/pom.xml
- redpen-cli/src/main/java/cc/redpen/Main.java
The following is the updated help message.
```
usage: redpen-cli [Options] [<INPUT FILE>]
Validate input documents with specified configuration settings.
Options:
-c,--conf <CONF FILE>                Configuration file (REQUIRED)
-f,--format <FORMAT>                 Input file format
(markdown,plain,wiki,asciidoc,latex,rest)
-h,--help                            Displays this help information and exits
-l,--limit <LIMIT NUMBER>            Error limit number
-L,--lang <LANGUAGE>                 Language of error messages
-r,--result-format <RESULT FORMAT>   Output result format
(json,json2,plain,plain2,xml)
-s,--sentence <INPUT SENTENCES>      Input sentences
-t,--threshold <THRESHOLD>           Threshold of error level (info, warn,
error)
-v,--version                         Displays …
```
> Enrich help message

- redpen-core/src/main/java/cc/redpen/validator/sentence/OkuriganaValidator.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/OkuriganaValidatorTest.java
Hello,
I'm considering the improvement of Okurigana feature.
Please confirm whether the reviced code is acceptable or not.
[Improved feature]
Improve Okurigana feature
[Issue]
If the verb of "消費する" is included with the sentnce,
The unexpected issues will be detected as 不正な送り仮名.
[Measure]
The unexpected issues won't be deteced 
if the existing code is replaced with the reviced code.
The existing code
static {
invalidOkurigana = new HashSet<>();
invalidOkurigana.add("費さ");
invalidOkurigana.add("費し");
invalidOkurigana.add("費す");
invalidOkurigana.add("費せ");
invalidOkurigana.add("費そ");
}
The reviced code
static {
invalidOkuriganaTokens.add(new ExpressionRule().addElement(new TokenElement("費さ", asList("動詞", "自立"), 0)));
invalidOkuriganaTokens.add(new ExpressionRule().addElement(new …
> Improve Okurigana feature

- redpen-core/src/main/java/cc/redpen/validator/sentence/JapaneseStyleValidator.java
I added the option to force the DEARU mode. Default mode is unchanged (auto-detection).
The original code determines if the document is in DEARU/DESUMASU by the superior occurrence, and it works in most cases. But many of our students write their report by using DESUMASU while it should be DEARU, so I needed to fix the mode to DEARU even when DESUMASU is superior.
> added ForceDearu option + fixed MASU detection pattern

- redpen-cli/bin/redpen
- redpen-server/bin/redpen-server
Fix type in error message.
Before `execututable` to after `executable`
> Fix typo in error message.

- redpen-core/src/main/java/cc/redpen/parser/BaseDocumentParser.java
Ref #869 
I make the output formatter have not only input file name but also the paths. The following is an example of the changes. 
Is this work for you @tsuyoshicho ?
```
$ bin/redpen sample-doc/en/sampledoc-en.md
...
[2020-01-03 23:17:09.819][INFO ] cc.redpen.validator.JavaScriptValidator - JavaScript validators directory: js
sample-doc/en/sampledoc-en.md:3: ValidationError[SentenceLength], The length of the sentence (195) exceeds the maximum of 120. at line: Some software tools work in more than one machine, and such distributed (cluster)systems can handle huge data or tasks, because such software tools make use of large amount of computer resources.
sample-doc/en/sampledoc-en.md:3: ValidationError[SymbolWithSpace], Need whitespace after symbol ")". at line: Some software tools work …
```
> Add relative path of input files in output format

- redpen-core/src/main/java/cc/redpen/validator/sentence/JapaneseBrokenExpressionValidator.java
- redpen-core/src/test/java/cc/redpen/validator/sentence/JapaneseBrokenExpressionValidatorTest.java
JapaneseBrokenExpression would cause false positives for potential verb.
It would assert error for "食べられる", "見られる", "寝られる", and so on.
What I did:
* Added tests for checking this
* Fixed code (JapaneseBrokenExpression only).
* Added special case handling
The tokenizer will parse ”見れる" as one token.
It might depends on dicts of Kuromoji or so.
This issue looks similar https://github.com/takuyaa/kuromoji.js/issues/28
I think we need to add other special cases (if there are).
It's better to use BaseForm in this logic
```java
q.getSurface().startsWith("られ")
```
Best way.
```java
q.getBaseForm().equals("られる")
```
But to get baseForm, we need to change TokenElement and NoelogdJapaneseTokenizer.
It looks other Validators won't use BaseForm of each tokens, and it's only necessary with Japanese. …
> Fixed false positive for "食べられる" (potential verb) by JapaneseBrokenExpression

- redpen-cli/src/main/java/cc/redpen/Main.java
- redpen-core/src/main/java/cc/redpen/RedPen.java
- redpen-server/src/main/java/cc/redpen/server/api/RedPenResource.java
`redpen-server` was not working correctly with the new feature of "error threshold" that there was no way to specify to get `info` or `warn`.
With this commit they can request an error level by sending `errorLevel` within the POST form such as:
```
var formData = {
'document': body.getText(),
'lang' : 'ja',
'format' : 'json2',
'documentParser' : 'plain',
'config' : configs,
'errorLevel' : 'warn'
};
```
> Added the error level threshold feature to redpen-server

- mvnw.cmd
fileformat of the file is DOS. So you can see original diff via:
https://github.com/redpen-cc/redpen/pull/882/commits/b85797dde9640e6dc2387e601e760e92d12eb789?w=1
> Fix typo in mvnw.cmd
