pom.xml, redpen-cli/pom.xml, redpen-core/pom.xml, redpen-server/pom.xml, run_test.sh
Align name of the output file with the version of the redpen-cli command.
=> Version bump to 1.1

redpen-core/src/main/java/cc/redpen/formatter/XMLFormatter.java, redpen-core/src/main/java/cc/redpen/model/Sentence.java, redpen-core/src/main/java/cc/redpen/parser/LineOffset.java, redpen-core/src/main/java/cc/redpen/parser/markdown/ToFileContentSerializer.java, redpen-core/src/main/java/cc/redpen/validator/ValidationError.java, redpen-core/src/main/java/cc/redpen/validator/Validator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/EndOfSentenceValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/InvalidExpressionValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/InvalidSymbolValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/SpaceBeginningOfSentenceValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/SpaceBetweenAlphabeticalWordValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/SuggestExpressionValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/SymbolWithSpaceValidator.java, redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java, redpen-core/src/test/java/cc/redpen/PlainTextParserTest.java, redpen-core/src/test/java/cc/redpen/WikiParserTest.java, redpen-core/src/test/java/cc/redpen/formatter/XMLFormatterTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/EndOfSentenceValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/InvalidExpressionValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/InvalidSymbolValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/SpaceBetweenAlphabeticalWordValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/SuggestExpressionValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/SymbolWithSpaceValidatorTest.java
=> Implementation of offset information to validation errors

redpen-cli/bin/redpen, redpen-cli/sample/conf/logback.xml, redpen-cli/src/main/java/cc/redpen/Main.java, redpen-cli/src/test/java/cc/redpen/MainTest.java
- enhanced error messages when parameters are not specified
Ref #383
=> redpen-383 Enhance error messages

redpen-core/src/main/java/cc/redpen/model/Sentence.java, redpen-core/src/main/java/cc/redpen/parser/SentenceExtractor.java, redpen-core/src/main/java/cc/redpen/parser/WikiParser.java, redpen-core/src/main/java/cc/redpen/parser/markdown/MergedCandidateSentence.java, redpen-core/src/main/java/cc/redpen/parser/markdown/ToFileContentSerializer.java, redpen-core/src/main/java/cc/redpen/util/EndOfSentenceDetector.java, redpen-core/src/main/java/cc/redpen/util/Pair.java, redpen-core/src/test/java/cc/redpen/parser/SentenceExtractorTest.java, redpen-core/src/test/java/cc/redpen/util/EndOfSentenceDetectorTest.java
redpen-370 Refactoring: SentenceExtractor
- added SentenceExtractor.extract method outputs sentence positions
=> redpen-370 Refactoring: SentenceExtractor

redpen-core/src/main/java/cc/redpen/formatter/JSONFormatter.java, redpen-core/src/main/java/cc/redpen/model/Section.java, redpen-core/src/main/java/cc/redpen/model/Sentence.java, redpen-core/src/main/java/cc/redpen/parser/WikiParser.java, redpen-core/src/main/java/cc/redpen/validator/ValidationError.java, redpen-core/src/main/java/cc/redpen/validator/section/DuplicatedSectionValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/KatakanaSpellCheckValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/SpaceBeginningOfSentenceValidator.java, redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java, redpen-core/src/test/java/cc/redpen/PlainTextParserTest.java, redpen-core/src/test/java/cc/redpen/WikiParserTest.java, redpen-core/src/test/java/cc/redpen/formatter/JSONFormatterTest.java, redpen-core/src/test/java/cc/redpen/model/DocumentCollectionTest.java, redpen-core/src/test/java/cc/redpen/model/DocumentTest.java, redpen-core/src/test/java/cc/redpen/model/SectionTest.java
redpen-392 output position offset with JSONFormatter
=> redpen-392 output position offset with JSONFormatter

redpen-cli/sample/conf/logback.xml
=> Fix error messages by removal of file appender in logback.xml

redpen-core/src/main/java/cc/redpen/parser/markdown/MergedCandidateSentence.java
=> Fix a Markdown parser failure

redpen-core/src/main/java/cc/redpen/ConfigurationLoader.java, redpen-core/src/main/java/cc/redpen/config/Configuration.java, redpen-core/src/main/java/cc/redpen/config/SymbolTable.java, redpen-core/src/test/java/cc/redpen/ConfigurationLoaderTest.java, redpen-core/src/test/java/cc/redpen/config/ConfigurationRedPenBuilderTest.java
=> Add symbol variations with the **type** attribute

redpen-server/src/main/webapp/index.html
Hi, I've patched reflected XSSs.
=> Patching reflected XSSs

redpen-core/src/main/java/cc/redpen/util/DictionaryLoader.java, redpen-core/src/main/java/cc/redpen/validator/Validator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/DoubledWordValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/InvalidExpressionValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/InvalidWordValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/KatakanaSpellCheckValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/SpellingValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/StartWithCapitalLetterValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/SuggestExpressionValidator.java, redpen-core/src/test/java/cc/redpen/util/DictionaryLoaderTest.java
load dictionary files from cache if available
=> cache user dictionary files

redpen-cli/src/main/java/cc/redpen/Main.java, redpen-cli/src/test/java/cc/redpen/MainTest.java
fixed #379 load configuration file from default path if not specified
=> fixed #379 load configuration file from default path if not specified

redpen-server/src/main/java/cc/redpen/server/api/RedPenResource.java
* Updated the HTTP API call /rest/document/validate to optionally take a config field, which can contain the XML from a RedPen configuration file
* Added a 'format' parameter to /rest/document/validate to allow callers to specify the result format, as per /rest/document/validate/json
=> HTTP API Updates

redpen-server/src/main/java/RedPenRunner.java
I removed the -c option since the option is not supported from v1.0.
=> Remove -c option from redpen server

redpen-server/src/main/java/RedPenRunner.java
Make redpen server flush the correct version.
=> Correct server version inconsistency

redpen-cli/src/main/java/cc/redpen/Main.java
Show supported input/output format in help string.
http://redpen.cc/docs/latest/format.html
http://redpen.cc/docs/latest/output.html
=> User friendly input/output help

redpen-core/src/main/java/cc/redpen/validator/JavaScriptValidator.java
update JavaDoc to follow the latest Validator interface
=> update JavaDoc to follow the latest Validator interface

redpen-core/pom.xml, redpen-core/src/main/java/cc/redpen/parser/AsciiDocParser.java, redpen-core/src/main/java/org/asciidoctor/RedPenTreeProcessor.java, redpen-core/src/test/java/cc/redpen/AsciiDocParserTest.java
* Implemented support for offset calculation is document and section header text
* Added JavaDoc to the more obscure methods in the AsciiDoc implementation
* Added some of Ito-san's AsciiDoc header offset tests
=> AsciiDoc parser improvements

pom.xml, redpen-cli/bin/redpen, redpen-cli/src/main/assembly/executable.xml, redpen-distribution/pom.xml, redpen-distribution/src/main/assembly/assembly.xml, redpen-server/bin/redpen-server, redpen-server/src/main/java/RedPenRunner.java
=> All in one package

redpen-server/bin/redpen-server
Fix redpen-server runtime error in Homebrew installation.
=> Fix redpen-server failure in the homebrew environment

.slugignore, redpen-cli/src/main/assembly/executable.xml, redpen-distribution/src/main/assembly/assembly.xml
Fix build failure in Heroku environment.
=> Reduce outputs for Heroku build failure

redpen-cli/bin/redpen, redpen-cli/src/main/java/cc/redpen/Main.java, redpen-cli/src/test/java/cc/redpen/MainTest.java
fallback to redpen-conf-[lang].xml when specified configuration file or redpen-conf.xml is not found
=> fallback to redpen-conf-[lang].xml when specified configuration file or redpen-conf.xml is not found

redpen-cli/sample/conf/redpen-conf-en.xml, redpen-cli/sample/conf/redpen-conf-ja.xml, redpen-cli/sample/js/validator.js.example, redpen-cli/src/main/assembly/executable.xml
=> add validator.js example

redpen-core/src/main/java/cc/redpen/parser/AsciiDocParser.java, redpen-core/src/main/java/org/asciidoctor/RedPenTreeProcessor.java, redpen-core/src/test/java/cc/redpen/AsciiDocParserTest.java
Added support for AsciiDoc lists
=> Updates to AsciiDoc support

redpen-core/src/main/java/cc/redpen/model/Document.java, redpen-core/src/test/java/cc/redpen/RedPenTest.java, redpen-core/src/test/java/cc/redpen/model/DocumentCollectionTest.java, redpen-core/src/test/java/cc/redpen/model/DocumentTest.java, redpen-core/src/test/java/cc/redpen/validator/JavaScriptValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/section/DuplicatedSectionValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/ContractionValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/DoubledWordValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/EndOfSentenceValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/InvalidExpressionValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/InvalidSymbolValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/InvalidWordValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/JapaneseStyleValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/KatakanaSpellCheckValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/SpaceBeginningOfSpenceValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/SpaceBetweenAlphabeticalWordValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/SpellingValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/StartWithCapitalLetterValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/SuccessiveWordValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/sentence/SymbolWithSpaceValidatorTest.java
remove DocumentBuilder#addSentence(String content, int lineNumber)
this method is used only by test cases.
=> remove DocumentBuilder#addSentence(String content, int lineNumber)

redpen-cli/sample/js/validator.js.example, redpen-core/src/main/java/cc/redpen/validator/JavaScriptValidator.java, redpen-core/src/main/java/cc/redpen/validator/Validator.java, redpen-core/src/test/java/cc/redpen/validator/HardcodedMessageValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/JavaScriptValidatorTest.java, redpen-core/src/test/java/cc/redpen/validator/ValidatorTest.java
introduce Validate#addError method which you can add non-localized/hard-coded ValidationError
=> introduce Validate#addError method which you can add non-localized/hard-coded ValidationError

redpen-cli/sample/sample-doc/en/sampledoc-en.tex, redpen-cli/sample/sample-doc/ja/sampledoc-ja.tex, redpen-cli/src/main/java/cc/redpen/Main.java, redpen-server/src/main/webapp/index.html
=> Misc LaTeX related updates

redpen-core/src/main/java/cc/redpen/validator/JavaScriptValidator.java
Just put a info level message when js directory is missing.
=> Just put a info level message when js directory is missing.

redpen-cli/bin/redpen.bat
=> Fix character corruption in Windows

redpen-core/src/main/java/cc/redpen/validator/JavaScriptValidator.java
Ref #501 
I am not 100% sure but this patch fix the behavior in my environment (MacOSX).
=> Load js directory from $REDPEN_HOME/js

redpen-core/src/test/java/cc/redpen/formatter/JSONBySentenceFormatterTest.java
=> Remove redundant assert

redpen-core/src/main/java/cc/redpen/validator/sentence/KatakanaSpellCheckValidator.java, redpen-core/src/test/java/cc/redpen/validator/sentence/KatakanaSpellCheckValidatorTest.java
=> Add list propery for KatakanaSpellCheck

redpen-core/src/main/java/cc/redpen/validator/sentence/KatakanaSpellCheckValidator.java, redpen-core/src/test/java/cc/redpen/validator/sentence/KatakanaSpellCheckValidatorTest.java
=> Add a parameter to disable default resources for KakatanaSpellCheck

redpen-core/src/main/java/cc/redpen/config/SymbolTable.java, redpen-core/src/main/java/cc/redpen/formatter/Formatter.java, redpen-core/src/main/java/cc/redpen/formatter/JSONBySentenceFormatter.java, redpen-core/src/main/java/cc/redpen/formatter/JSONFormatter.java, redpen-core/src/main/java/cc/redpen/model/Sentence.java, redpen-core/src/main/java/cc/redpen/parser/AsciiDocParser.java, redpen-core/src/main/java/cc/redpen/parser/MarkdownParser.java, redpen-core/src/main/java/cc/redpen/parser/SentenceExtractor.java, redpen-core/src/main/java/cc/redpen/util/DictionaryLoader.java, redpen-core/src/main/java/cc/redpen/util/SpellingUtils.java, redpen-core/src/main/java/cc/redpen/validator/Validator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/DoubledJoshiValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/KatakanaEndHyphenValidator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/KatakanaSpellCheckValidator.java, redpen-core/src/main/java/org/asciidoctor/RedPenTreeProcessor.java, redpen-server/src/main/java/cc/redpen/server/api/RedPenResource.java
fix javadoc errors
remove self-enclosing tags
add @parameter / @return descriptions
=> javadocfix

pom.xml, redpen-cli/pom.xml, redpen-core/pom.xml, redpen-distribution/pom.xml, redpen-plugin/pom.xml, redpen-server/pom.xml, run_test.sh
version 1.4.1 has been released and we're now working on 1.4.2-SNAPSHOT.
"-SNAPSHOT" is a version suffix required by maven.
=> version 1.4.2-SNAPSHOT

redpen-cli/src/main/java/cc/redpen/Main.java, redpen-core/src/main/java/cc/redpen/parser/asciidoc/AsciiDocParser.java, redpen-core/src/main/java/cc/redpen/parser/asciidoc/Line.java, redpen-core/src/main/java/cc/redpen/parser/asciidoc/Model.java, redpen-server/src/main/java/cc/redpen/server/api/RedPenResource.java, redpen-server/src/main/java/cc/redpen/server/api/RedPenService.java
=> fix javadoc errors

redpen-core/src/main/java/cc/redpen/validator/sentence/SuggestExpressionValidator.java, redpen-core/src/test/java/cc/redpen/validator/sentence/SuggestExpressionValidatorTest.java
Hello,
I've fixed the error message from the SuggestExpression validator.
Best,
-t
=> Fixed the error message of the SuggestExpression validator

redpen-core/src/main/java/cc/redpen/validator/sentence/NumberFormatValidator.java, redpen-core/src/test/java/cc/redpen/validator/sentence/NumberFormatValidatorTest.java
Otherwise average text is full of errors
=> Ignore years by default in NumberFormatValidator

redpen-server/bin/redpen-server.bat
Hello,
I've ported the redpen-server launcher script to Windows.
It should work on Windows XP or better.
This PR intends to resolve #545.
Thank you.
-t
=> Added redpen-server launcher script for Windows

redpen-core/src/main/java/cc/redpen/parser/MarkdownParser.java, redpen-core/src/main/java/cc/redpen/parser/markdown/ToFileContentSerializer.java, redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java
Offsets were reported incorrectly
=> Fix broken handling of spaces at the end of line in markdown parser

redpen-core/src/main/java/cc/redpen/config/Configuration.java, redpen-core/src/main/java/cc/redpen/config/SymbolTable.java, redpen-core/src/main/java/cc/redpen/util/LanguageDetector.java, redpen-core/src/main/java/cc/redpen/util/StringUtils.java, redpen-core/src/test/java/cc/redpen/config/SymbolTableTest.java, redpen-core/src/test/java/cc/redpen/util/LanguageDetectorTest.java, redpen-server/src/test/java/cc/redpen/server/api/RedPenServiceTest.java
Uses correct symbols and language autodetection
=> Add basic Russian support

redpen-core/src/main/java/cc/redpen/validator/section/ParagraphStartWithValidator.java, redpen-core/src/test/java/cc/redpen/validator/section/ParagraphStartWithValidatorTest.java
* Report errors for invalid start (before was only no start)
* Report errors for second and subsequent paragraphs properly
=> Fix paragraph start validator

redpen-core/src/main/java/cc/redpen/parser/markdown/ToFileContentSerializer.java, redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java
This patch fixes the exception reported in #574
=> Hot fix of exception in Markdown parser

redpen-core/pom.xml, redpen-server/pom.xml, redpen-server/src/main/java/RedPenRunner.java, redpen-server/src/main/java/cc/redpen/server/api/RedPenService.java
add -c option to RedPenRunner for specifying configuraiton xml for server instance
=> server-config

.gitignore, redpen-core/src/main/java/cc/redpen/parser/markdown/MergedCandidateSentence.java, redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java
=> Fix redpen-578

redpen-core/src/test/java/cc/redpen/config/ConfigurationTest.java
=> Remove slash for splitting directory in order to fix windows support

redpen-core/src/main/java/cc/redpen/parser/SentenceExtractor.java, redpen-core/src/main/java/cc/redpen/util/EndOfSentenceDetector.java, redpen-core/src/test/java/cc/redpen/parser/SentenceExtractorTest.java, redpen-core/src/test/java/cc/redpen/util/EndOfSentenceDetectorTest.java
This patch simplify the regex pattern. 
This pull request for handling problem in IntelliJ plugin (https://github.com/redpen-cc/redpen-intellij-plugin/issues/7).
=> [WIP] Modify regex pattern in SentenceExtractor

redpen-server/pom.xml, redpen-server/src/main/resources/logback.xml, redpen-server/src/test/java/cc/redpen/server/api/CORSFilterTest.java, redpen-server/src/test/java/cc/redpen/server/api/RedPenResourceTest.java, redpen-server/src/test/java/cc/redpen/server/api/RedPenServiceTest.java, redpen-server/src/test/java/ui/RedPenDemoTest.java, redpen-server/src/test/resources/logback-test.xml
with this change, RedPenDemoTest will automatically start Jetty server when port 8080 is available
=> autorun Jetty in RedPenDemoTest

redpen-core/src/main/java/cc/redpen/validator/sentence/InvalidSymbolValidator.java, redpen-core/src/test/java/cc/redpen/validator/sentence/InvalidSymbolValidatorTest.java
=> redpen-613 Excluding floating point numbers in InvalidSymbolValidator

.travis.yml, appveyor.yml, redpen-server/pom.xml, redpen-server/src/test/java/ui/PhantomJSInstaller.java, redpen-server/src/test/java/ui/RedPenDemoTest.java
auto-install phantomjs on Windows/Mac/Linux environment
=> auto-install phantomjs

redpen-core/pom.xml, redpen-core/src/main/java/cc/redpen/validator/ValidatorFactory.java, redpen-core/src/test/java/cc/redpen/NoDefaultConstructorValidator.java, redpen-core/src/test/java/cc/redpen/validator/ValidatorFactoryTest.java
simplify ValidatorFactory using reflections lib.
=> simplify ValidatorFactory using reflections lib.

redpen-server/src/main/java/cc/redpen/server/api/RedPenResource.java, redpen-server/src/test/java/cc/redpen/server/api/RedPenResourceTest.java
Hello, I've fixed redpen-server so that it declares somewhat more accurate MIME types.
This PR intends to resolve #623 and #624 .
Thanks.
-t
=> MIME type related fixes

redpen-core/src/main/java/cc/redpen/RedPen.java
Hot fix for the server does not work. 
This fix is going to be reverted before merging #632.
=> Hot fix server does not annotation in the begining

redpen-cli/pom.xml, redpen-cli/src/main/java/cc/redpen/Main.java, redpen-cli/src/test/java/cc/redpen/MainTest.java
=> redpen-497

redpen-cli/sample/conf/redpen-conf-en.xml, redpen-cli/sample/conf/redpen-conf-ja.xml
#641 Enhance default settings adding new validators
Updated validators in default setting files for RedPen CLI
=> redpen-641 Enhance default settings adding new validators

redpen-core/src/main/java/cc/redpen/RedPen.java
=> Revert "Hot fix server does not annotation in the begining"

redpen-core/src/main/java/cc/redpen/model/Document.java, redpen-core/src/main/java/cc/redpen/parser/MarkdownParser.java, redpen-core/src/main/java/cc/redpen/parser/ParserUtils.java, redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java, redpen-core/src/test/java/cc/redpen/SampleDocumentGeneratorTest.java, redpen-core/src/test/java/cc/redpen/model/DocumentTest.java
=> Do not create Level 0 seciton in Markdown when the input document start from a section

redpen-core/src/main/java/cc/redpen/validator/sentence/SpaceBetweenAlphabeticalWordValidator.java, redpen-core/src/test/java/cc/redpen/validator/sentence/SpaceBetweenAlphabeticalWordValidatorTest.java
This fix to handling of multi-byte parenthesis characters.
=> Add handling to skip error when the parenthesis are multi-byte character

redpen-core/src/main/java/cc/redpen/validator/section/VoidSectionValidator.java, redpen-core/src/test/java/cc/redpen/validator/section/VoidSectionValidatorTest.java
=> Add limit parameter to VoidSection

redpen-core/src/main/java/cc/redpen/validator/sentence/JapaneseAmbiguousNounConjunctionValidator.java, redpen-core/src/test/java/cc/redpen/validator/sentence/JapaneseAmbiguousNounConjunctionValidatorTest.java
- added list parameter for skip list
=> Enhance Ambiguous noun conjunction 

redpen-core/src/main/java/cc/redpen/parser/asciidoc/AsciiDocParser.java, redpen-core/src/test/java/cc/redpen/AsciiDocParserTest.java
=> Implement handling of labeled single-line list

redpen-core/src/main/java/cc/redpen/parser/common/Line.java, redpen-core/src/main/java/cc/redpen/parser/review/ReVIEWParser.java, redpen-core/src/test/java/cc/redpen/AsciiDocParserTest.java, redpen-core/src/test/java/cc/redpen/parser/review/ReVIEWParserTest.java
**@kw** tag
--------------
Extract only keyword from **@kw** tag. For example in the following example, the parser extracts only xxx from **@kw** tag.
```
this is @<kw>{xxx, yyyy}.
```
**@href** tag
---------------
Extract only description from **@href** tag. For example in the following example, the parser extracts only yyy from **@href** tag.
```
this is @<href>{http://redpen.cc, yyyy}.
```
=> Improvement Re:VIEW keyword and href handling

redpen-core/src/main/java/cc/redpen/parser/asciidoc/AsciiDocParser.java, redpen-core/src/test/java/cc/redpen/AsciiDocParserTest.java, redpen-core/src/test/java/cc/redpen/parser/asciidoc/AsciiDocTest.java
=> Fixed handling of attribute of images

redpen-core/src/main/java/cc/redpen/validator/sentence/JapaneseStyleValidator.java, redpen-core/src/test/java/cc/redpen/validator/sentence/JapaneseStyleValidatorTest.java
This is  just a hotfix. I will reimplement with rule based validator.
=> Fix mismatch in JapaneseStyle.

redpen-server/bin/redpen-server, redpen-server/bin/redpen-server.bat
=> Make configuration file specify in redpen-server command

redpen-core/src/main/java/cc/redpen/model/Document.java, redpen-core/src/main/java/cc/redpen/validator/section/DuplicatedSectionValidator.java, redpen-core/src/test/java/cc/redpen/validator/section/DuplicatedSectionValidatorTest.java
Ref https://gist.github.com/masanobuimai/edf9fd4b112b36dacd00af63708e8c21
=> Fix duplicatedsection exception

NOTICE.md, redpen-core/src/main/java/cc/redpen/tokenizer/TokenElement.java, redpen-core/src/main/java/cc/redpen/validator/sentence/DoubledJoshiValidator.java, redpen-core/src/test/java/cc/redpen/validator/sentence/DoubledJoshiValidatorTest.java
=> Introduced min_interval opiton to DoubledJoshi

README.md
=> Fix spell miss

redpen-core/src/main/java/cc/redpen/validator/Validator.java, redpen-core/src/main/java/cc/redpen/validator/sentence/SuggestExpressionValidator.java, redpen-core/src/test/java/cc/redpen/validator/sentence/SuggestExpressionValidatorTest.java, redpen-server/src/main/webapp/index.html
=> Redpen 653

.gitignore, redpen-server/src/main/webapp/index.html, redpen-server/src/main/webapp/js/karma.conf.js, redpen-server/src/main/webapp/js/redpen-ui.js, redpen-server/src/main/webapp/js/test/redpen-ui-spec.js, redpen-server/src/main/webapp/package.json
=> [WIP] Add Unit tests for UI

redpen-core/src/main/java/cc/redpen/validator/JavaScriptValidator.java, redpen-core/src/test/java/cc/redpen/validator/JavaScriptValidatorTest.java
You can specify validator specific parameters with [ValidatorName]-[parametername].
e.g.
To specify my_parameter to 10 for MyValidator.js, declarete as follows:
<property name="MyValidator-my_parameter" value="10"/>
=> capability to specify script specific parameter

redpen-server/bin/redpen-server.bat
=> Fix redpen-server.bat

redpen-core/src/main/java/cc/redpen/validator/section/ParagraphNumberValidator.java
=> Fix error mssage of ParagraphNumber

redpen-core/src/main/java/cc/redpen/validator/sentence/WordNumberValidator.java, redpen-core/src/test/java/cc/redpen/validator/sentence/WordNumberValidatorTest.java
=> Fix wordcount

redpen-core/src/main/java/cc/redpen/validator/ValidatorFactory.java, redpen-core/src/test/java/cc/redpen/validator/ValidatorFactoryTest.java
make JS validators visible to Web UI
=> make JS validators visible to Web UI

redpen-core/src/main/java/cc/redpen/validator/sentence/HankakuKanaValidator.java, redpen-core/src/test/java/cc/redpen/validator/sentence/HankakuKanaValidatorTest.java
=> Fix HankakukKana validator

redpen-cli/src/main/java/cc/redpen/Main.java, redpen-cli/src/test/java/cc/redpen/MainTest.java
=> Add sentence option

redpen-core/src/main/java/cc/redpen/validator/Validator.java, redpen-core/src/test/java/cc/redpen/validator/sentence/SpaceBetweenAlphabeticalWordValidatorTest.java
=> Revert Validator.getString

redpen-core/src/main/java/cc/redpen/validator/ValidatorFactory.java, redpen-core/src/main/java/cc/redpen/validator/sentence/SpaceBeginningOfSentenceValidator.java, redpen-core/src/test/java/cc/redpen/validator/ValidatorFactoryTest.java
=> Support validator deprecation

redpen-core/src/main/java/cc/redpen/parser/markdown/ToFileContentSerializer.java, redpen-core/src/test/java/cc/redpen/MarkdownParserTest.java
=> Support headings with image in Markdown parser

redpen-server/src/main/java/RedPenRunner.java
=> Make server stop with password

redpen-core/src/main/java/cc/redpen/tokenizer/WhiteSpaceTokenizer.java, redpen-core/src/test/java/cc/redpen/PlainTextParserTest.java, redpen-core/src/test/java/cc/redpen/tokenizer/WhiteSpaceTokenizerTest.java
This pull requests closes #754
=> Improve handling quotations

redpen-core/src/test/java/cc/redpen/validator/sentence/JapaneseStyleValidatorTest.java
=> Add a test case for JapaneseStyleValidator

redpen-server/src/main/java/cc/redpen/server/api/RedPenConfigurationResource.java, redpen-server/src/main/java/cc/redpen/server/api/RedPenResource.java, redpen-server/src/main/java/cc/redpen/server/api/RedPenService.java, redpen-server/src/main/webapp/css/redpen.css, redpen-server/src/main/webapp/index.html, redpen-server/src/main/webapp/js/redpen-ui.js, redpen-server/src/main/webapp/js/redpen.js, redpen-server/src/test/java/cc/redpen/server/api/RedPenConfigurationResourceTest.java, redpen-server/src/test/java/cc/redpen/server/api/RedPenServiceTest.java
=> Add feature to export configuration which closes #663

redpen-cli/src/main/java/cc/redpen/Main.java, redpen-server/bin/redpen-server, redpen-server/bin/redpen-server.bat, redpen-server/src/main/java/RedPenRunner.java
=> Make language of error messages selectable

redpen-core/src/main/java/cc/redpen/config/ConfigurationLoader.java
=> Disable DTD

redpen-cli/sample/conf/redpen-conf-en.xml, redpen-cli/sample/conf/redpen-conf-ja.xml, redpen-core/src/main/java/cc/redpen/config/ConfigurationLoader.java, redpen-core/src/main/java/cc/redpen/config/ValidatorConfiguration.java, redpen-core/src/main/java/cc/redpen/formatter/JSONBySentenceFormatter.java, redpen-core/src/main/java/cc/redpen/formatter/JSONFormatter.java, redpen-core/src/main/java/cc/redpen/formatter/PlainFormatter.java, redpen-core/src/main/java/cc/redpen/formatter/XMLFormatter.java, redpen-core/src/main/java/cc/redpen/validator/ValidationError.java, redpen-core/src/main/java/cc/redpen/validator/Validator.java, redpen-core/src/main/resources/default-resources/spellchecker/spellchecker-en.dat, redpen-core/src/test/java/cc/redpen/config/ConfigurationLoaderTest.java, redpen-core/src/test/java/cc/redpen/config/ValidatorConfigurationTest.java, redpen-core/src/test/java/cc/redpen/formatter/JSONBySentenceFormatterTest.java, redpen-core/src/test/java/cc/redpen/formatter/JSONFormatterTest.java, redpen-core/src/test/java/cc/redpen/formatter/PlainFormatterTest.java, redpen-core/src/test/java/cc/redpen/formatter/XMLFormatterTest.java
=> Add error level to VdalitaorConfiguration

redpen-core/src/main/java/cc/redpen/validator/document/JapaneseExpressionVariationValidator.java, redpen-core/src/test/java/cc/redpen/validator/document/JapaneseExpressionVariationValidatorTest.java
To enhance JapaneseExpresionVariation, I added a character normalization step to detect the word pairs which have almost the same readings.
=> Add character normalization to detect same readings

.travis.yml, redpen-core/pom.xml, redpen-core/src/main/java/cc/redpen/parser/latex/LaTeXProcessor.java, redpen-core/src/main/java/cc/redpen/parser/latex/StreamParser.java, redpen-core/src/test/java/cc/redpen/validator/JavaScriptValidatorTest.java
=> [WIP] Support Java9

redpen-server/src/main/java/cc/redpen/server/api/RedPenConfigurationResource.java, redpen-server/src/main/java/cc/redpen/server/api/RedPenService.java
Fix https://github.com/redpen-cc/redpen/issues/820
=> [WIP] Specify configuration for lang

redpen-core/src/main/java/cc/redpen/validator/document/UnexpandedAcronymValidator.java, redpen-core/src/test/java/cc/redpen/validator/document/UnexpandedAcronymValidatorTest.java
This pull request fixes  #828.
=> Refactor unexpanded acronym

redpen-core/src/main/java/cc/redpen/parser/rest/ReSTParser.java, redpen-core/src/test/java/cc/redpen/parser/rest/ReSTParserTest.java
Ref https://github.com/redpen-cc/redpen/issues/840
=> Support new line style in reStructredtext

redpen-core/src/main/java/cc/redpen/parser/review/ReVIEWParser.java, redpen-core/src/test/java/cc/redpen/parser/review/ReVIEWParserTest.java
ref: https://github.com/kmuto/review/blob/v2-stable/doc/format.md#referring-headings
```
=={intro} Introduction
```
=> Support labelled section in Re:VIEW

redpen-server/pom.xml
=> Fix security-problem updating jetty

.travis.yml, appveyor.yml, redpen-core/pom.xml
=> Fix build failure in JDK11

redpen-core/pom.xml, redpen-core/src/main/java/cc/redpen/tokenizer/NeologdJapaneseTokenizer.java, redpen-core/src/main/java/cc/redpen/validator/sentence/OkuriganaValidator.java
=> Increase the version of elasticsearch-analysis-kuromoji-neologd to 6.5.1
